# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    codeCoverageToolOption: 'Cobertura'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Unit tests'
    tasks: 'build'
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/AndroidFileExplorer/coverage/coverage.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/AndroidFileExplorer/src/main/java/'
    reportDirectory: '$(System.DefaultWorkingDirectory)/AndroidFileExplorer/coverage/'